# Generated by Django 5.1.5 on 2025-03-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='منتج بدون اسم', max_length=255, null=True, verbose_name='اسم المنتج')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='التصنيف')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='السعر')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='products/', verbose_name='صورة المنتج')),
            ],
        ),
    ]
