# Generated by Django 5.1.5 on 2025-03-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_product_description_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', max_length=255, null=True, upload_to='products/', verbose_name='صورة المنتج'),
        ),
    ]
