# Generated by Django 5.1.5 on 2025-03-21 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'منتج', 'verbose_name_plural': 'منتجات'},
        ),
    ]
