# Generated by Django 5.1.7 on 2025-04-11 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_dashboardstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='كمية')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الشركة')),
                ('street_address', models.CharField(max_length=200, verbose_name='عنوان الشارع')),
                ('apartment', models.CharField(blank=True, max_length=200, null=True, verbose_name='الشقة/الطابق')),
                ('town_city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email_address', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('visa', 'Visa')], max_length=20, verbose_name='طريقة الدفع')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='رقم البطاقة')),
                ('expiry_date', models.CharField(blank=True, max_length=5, null=True, verbose_name='تاريخ الانتهاء (MM/YY)')),
                ('cvv', models.CharField(blank=True, max_length=3, null=True, verbose_name='رمز الأمان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عملية الدفع',
                'verbose_name_plural': 'عمليات الدفع',
            },
        ),
        migrations.DeleteModel(
            name='DashboardStats',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='OrderDate',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='DeliveryAgent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Status',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='وكيل التوصيل'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL, verbose_name='العميل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pages.product', verbose_name='المنتج'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
