# Generated by Django 5.1.7 on 2025-04-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_driver.jpg', null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
    ]
