# Generated by Django 5.1.7 on 2025-04-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_userprofile_profile_image_userprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_agent_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_agent_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
