# Generated by Django 5.1.7 on 2025-05-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_alter_product_options_productrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'منتج', 'verbose_name_plural': 'منتجات'},
        ),
    ]
