# Generated by Django 5.1.7 on 2025-06-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
