# Generated by Django 5.1.7 on 2025-06-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_product_seller_lat_product_seller_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
