# Generated by Django 5.1.7 on 2025-06-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_userprofile_last_location_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تكلفة التوصيل'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='الوقت المقدر للتوصيل (بالدقائق)'),
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_distance',
            field=models.FloatField(blank=True, null=True, verbose_name='المسافة الكلية (كم)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
