# Generated by Django 5.1.7 on 2025-06-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_order_accepted_time_order_delivered_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='accepted_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='estimated_delivery_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='picked_up_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_distance',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_location_update',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
