# Generated by Django 5.1.5 on 2025-06-16 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.coupon'),
        ),
    ]
